### PR TITLE
Updated some SVGs to allow them to style inline

### PR DESCRIPTION
**Pull request by lee-chase**
It would be great if more of the SVGs could be easily styled out of the box. 

These SVGs have been updated to allow a simple primary / secondary state change in CSS. They follow the principle of building the SVGs from the back (first declared element) to the front (last declared element). There is no empty space as it cannot be styled, however a fill can be styled as transparent.

### CODE REVIEW

**Comment by cjolif** [comment]
:+1: for the feature.

**Comment by barlock** [comment]
These icons were [designed to be monochromatic](https://www.ibm.com/design/language/framework/visual/iconography#placement) so this isn't a feature we're going to support.

**Comment by cjolif** [comment]
@mbarlock even monochromatic you might want to switch the monochrome color to another one? Having some CSS classes would help with that.

**Comment by lee-chase** [comment]
Monochromatic or not it has not stopped designers I've worked with asking for them to be filled. In part this is because any icon used on an element that needs to indicate focus and / or hover will need at least need to change it's primary color. Where the icon is the button it's not always sufficient to change just the primary color.

**Comment by barlock** [comment]
Sure, but that already works without adding classes. Just set a `fill` and it will cascade to the svg.

Also these files are generated. Any changes made to these svgs need to happen in illustrator. I'm working on automating the export so changes like these can be made. Right now though we can't...

**Comment by barlock** [comment]
There's a discussion here https://github.com/IBM-Design/icons/pull/9#issuecomment-154274226

**Pull request closed without merging**
