### PR TITLE
Update that adds the Analytics Platform icons

### PR DESCRIPTION
**Pull request by mhsenkow**
This adds 29 icons that relate to data-visualization and data management

### CODE REVIEW

**Comment by mhsenkow** [comment]
@mbarlock :D....

**Comment by kevinSuttle** [comment]
I don't think we want to split these out into individual business units. Just put them on the top level.

**Comment by mhsenkow** [comment]
Ah I hadn't thought of it as business unit but rather what its subject matter is (these are all in relation to analytics)

**Comment by barlock** [comment]
Yeah I agree with @kevinSuttle I just got back from a trip and forgot to look at this today. I was going to talk with @hchughes about where she thought they should go, but my assumption is that _most_ of them are "object-based"

**Comment by barlock** [comment]
I ran the .ai files through the build, found a few strange things.
The following export a blank icon, I'm assuming it has a blank artboard. Can you remove them? (file_size): csv_16, json_16, xml_16

sql_16 doesn't have any text in it, was that on purpose?

Otherwise it worked without a hitch!

**Comment by barlock** [comment]
@hchughes Can you comment on where you think the icons should go? Or generally their fit into the set?

image
Here is a thumbnail of all of the 128 sizes.

**Comment by kevinSuttle** [comment]
@mhsenkow People use these icons in a lot of different ways, not just what they were intended for. That's why they should go on the top level.

**Comment by mhsenkow** [comment]
Right but I guess, what do you mean by top level? Outside of the folders entirely? You currently have three folders, action-based, object-oriented and the third, shouldn't these live within a folder too? Or should they break that prior form and just be sitting outside of those folders? @kevinSuttle

**Comment by kevinSuttle** [comment]
I think that's a question for @hchughes.

**Comment by mhsenkow** [comment]
@mbarlock yep those were on purpose, and ah yeah didn't know with the blank ones what to do, I'll fix that. Those icons, basically the visual designer decided they didn't want an option of using those icons at that size.

**Comment by mhsenkow** [comment]
bump @hchughes

**Comment by JasonCollier** [comment]
@mhsenkow Hayley is making a new commit with a subset of these icons that's going in today, so we're going to close this one.  Thanks!

**Pull request closed without merging**
