### PR TITLE
Add new icon for Notifications 

### PR DESCRIPTION
**Pull request by brianburnette**
This is an icon submission in regards to Issue #45 Notifications. We are testing it as a banner element as an alternative to the Announcement megaphone icon which doesn't quite hit on the same metaphor. 
[Iconography_Contribution_Notifications.zip](https://github.com/IBM-Design/icons/files/176732/Iconography_Contribution_Notifications.zip)

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
660 York Street, Suite 102,
San Francisco, CA 94110 USA

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by barlock** [comment]
Thanks for the submission. It seems this branch needs to be updated. Also instead of adding a zip file to the pr, please add the ai into the [src](https://github.com/IBM-Design/icons/tree/master/src/object-based) folder. In order for our scripts to automatically generate svgs and pngs to work, it needs to be in the same format as the rest of the ai files. It should be easy to copy a file and put your icon into it.

**Comment by brianburnette** [comment]
@mbarlock Sorry for the confusion, first time. I would have thought the ai would only go into src once it's been "approved". Is there something I need to do to update the branch?

**Comment by barlock** [comment]
Sense you're the first person to make a new icon submission we get to figure out the "approval" together. @hchughes is the one who gets to decide what changes, if any, need to be made to the icon before it can get approved. Once we figure out what this process looks like, I'll doc it and put it into the readme to make other's lives easier. To start with to fix your branch, it looks like your fork is out of date and you didn't actually make any changes so... Assuming you've set up this remote as `upstream`

run

```
$ git reset --hard upstream/master
# create the new icon file copying an existing one with the right sizes, for this pass its ok to not have all the sizes, but it would be good to add them later.
$ git add .
$ git commit -m "<commit message>"
$ git push origin master
```

And this pr will be updated! In the future it's best practice to create a new branch to make changes in rather than make them in `master`. Here's a good [guide](https://guides.github.com/introduction/flow/index.html).

**Comment by kevinSuttle** [comment]
Bump

**Comment by hchughes** [comment]
Hi @brianburnette! Thanks for this submission. I've gone ahead and reviewed it and I think it would be great to have a notifications icon in the language. I will take your file and make a few adjustments so that it matches the other icons in the language (some versions will need to be more outlined), some more solid like what you have, and we'll aim to put it up in the next week or two!

Thanks, Hayley

**Pull request closed without merging**
